version: "3.1"

services:
  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # ports:
    #   - "27017:27017"
    volumes:
      - ./../mydata:/data/db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    # ports:
    #   - "8000:8000"
    env_file: ./.env
    environment:
      NODE_ENV: $NODE_ENV
      DB_URL: mongodb://root:example@mongo:27017/
      DB_USER: $MONGODB_USER
      DB_PASSWORD: $MONGODB_PASSWORD
      DB_NAME: $MONGODB_DATABASE
      DB_PORT: $MONGODB_DOCKER_PORT
      PORT: $PORT
      JWT_SECRET_KEY: $JWT_SECRET_KEY
      JWT_EXPIRES: $JWT_EXPIRES
      ACTIVATION_SECRET: $ACTIVATION_SECRET
      SMPT_SERVICE: $SMPT_SERVICE
      SMPT_HOST: $SMPT_HOST
      SMPT_PORT: $SMPT_PORT
      SMPT_PASSWORD: $SMPT_PASSWORD
      SMPT_MAIL: $SMPT_MAIL
      STRIPE_API_KEY: $STRIPE_API_KEY
      STRIPE_SECRET_KEY: $STRIPE_SECRET_KEY
      CLOUDINARY_NAME: $CLOUDINARY_NAME
      CLOUDINARY_API_KEY: $CLOUDINARY_API_KEY
      CLOUDINARY_API_SECRET: $CLOUDINARY_API_SECRET
    depends_on:
      - mongo
  # Client service
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      NODE_ENV: PRODUCTION
      BACKEND_URL: https://backend.groupthree.shop
    # ports:
    #   - "82:80"
    depends_on:
      - backend

    # Volumes define
